import io
import json
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from ..models.design import DesignCreate

router = APIRouter(prefix="/export", tags=["export"])


@router.post("/json/{design_id}")
async def export_json(design_id: str):
    """Export a design as JSON."""
    # In production, fetch from Supabase
    data = {
        "id": design_id,
        "format": "forma-design-v1",
        "exportedAt": "2025-01-01T00:00:00Z",
        "parts": [],
    }
    content = json.dumps(data, indent=2)
    return StreamingResponse(
        io.BytesIO(content.encode()),
        media_type="application/json",
        headers={"Content-Disposition": f"attachment; filename=forma-design-{design_id}.json"}
    )


@router.post("/pdf/{design_id}")
async def export_pdf(design_id: str):
    """Export a design as PDF with bill of materials."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.pdfgen import canvas as pdf_canvas

        buf = io.BytesIO()
        c = pdf_canvas.Canvas(buf, pagesize=A4)
        w, h = A4

        # Title
        c.setFont("Helvetica-Bold", 24)
        c.drawString(50, h - 60, "Forma Design Report")

        # Design ID
        c.setFont("Helvetica", 12)
        c.drawString(50, h - 90, f"Design ID: {design_id}")
        c.drawString(50, h - 110, "Generated by Forma — 3D Furniture Physics Studio")

        # Bill of materials section
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, h - 160, "Bill of Materials")

        c.setFont("Helvetica", 12)
        c.drawString(50, h - 190, "Part name")
        c.drawString(300, h - 190, "Quantity")
        c.drawString(400, h - 190, "Price")

        c.save()
        buf.seek(0)
        return StreamingResponse(
            buf,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=forma-design-{design_id}.pdf"}
        )
    except ImportError:
        raise HTTPException(status_code=500, detail="PDF export not available")


@router.get("/share-link/{design_id}")
async def get_share_link(design_id: str):
    """Generate a public share link for a design."""
    return {
        "url": f"https://forma.vercel.app/view/{design_id}",
        "expires_at": None,
        "is_public": True,
    }
